### Registrar un nuevo usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Jahir Rocha",
    "email": "jahir@example.com",
    "password": "password123"
}

### Autenticar un usuario
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "jahir@example.com",
    "password": "password123"
}

### Obtener todos los productos (protegido)
GET http://localhost:3000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshU
###Obtener un producto por ID (protegido)
GET http://localhost:3000/products/679ae3c9a895981afecd77fd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshU

### Crear un nuevo producto (protegido)
POST http://localhost:3000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshU
Content-Type: application/json

{
    "name": "Tiramisú",
    "description": "Postre italiano con bizcocho empapado en café, queso mascarpone y cacao en polvo.",
    "price": 3,
    "image": "http://localhost:3000/uploads/tiramisu.jpg",
    "category": "Postres"
}

### Actualizar un producto (protegido)
PUT http://localhost:3000/products/679d8fe62fd1c8f0451d986d
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM4MTQ5NywiZXhwIjoxNzM4Mzg1MDk3fQ.YOAxMgY6k-UhDujdHgRRoztvlCG5EPGE7FibWH3v9Xc
Content-Type: application/json

{
    "image": "http://localhost:3000/uploads/brew.jpeg"

}

### Eliminar un producto (protegido)
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshU
DELETE http://localhost:3000/products/679ae3c9a895981afecd77fd


### Obtener el historial de compras del usuario (protegido)
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshU
GET http://localhost:3000/purchases

### Crear una nueva compra (protegido)
POST http://localhost:3000/purchases
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODM3NzUzOCwiZXhwIjoxNzM4MzgxMTM4fQ.kk9kwarnId10tCZ0QQMGWeCA8WeiDIcaFOVKJdXJshUt-Type: application/json
Content-Type: application/json

{
    "products": [
        {
            "productId": "679ae99aba6b45fd030af91c",
            "quantity": 2,

            "productId": "679ae99aba6b45fd030af91c",
            "quantity": 2
        }
    ],
    "paymentMethod": "tarjeta",
    "serveOption": "mesa"
}

### Actualizar el estado de una compra (protegido)
PUT http://localhost:3000/purchases/679ae9f6ba6b45fd030af926/status
Content-Type: application/json

{
    "status": "completed"
}