### Registrar un nuevo usuario
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Jahir Rocha",
    "email": "jahir@example.com",
    "password": "password123"
}

### Autenticar un usuario
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "jahir@example.com",
    "password": "password123"
}

### Obtener todos los productos (protegido)
GET http://localhost:3000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q
###Obtener un producto por ID (protegido)
GET http://localhost:3000/products/679ae3c9a895981afecd77fd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q

### Crear un nuevo producto (protegido)
POST http://localhost:3000/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q
Content-Type: application/json

{
    "name": "Capuccino",
    "description": "Bebida caliente con café y leche",
    "price": 5,
    "image": "https://example.com/brownie.jpg",
    "category": "Bebidas Calientes"
}

### Actualizar un producto (protegido)
PUT http://localhost:3000/products/679ae3c9a895981afecd77fd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q
Content-Type: application/json

{
    "price": 5.50
}

### Eliminar un producto (protegido)
DELETE http://localhost:3000/products/679ae3c9a895981afecd77fd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q


### Obtener el historial de compras del usuario (protegido)
GET http://localhost:3000/purchases
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q

### Crear una nueva compra (protegido)
POST http://localhost:3000/purchases
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIxMDYyMywiZXhwIjoxNzM4MjE0MjIzfQ.cbLIZygJb12KYBlKR5QfR3KCg_mf8RGIR-n2707HG9Q
Content-Type: application/json

{
    "products": [
        {
            "productId": "679ae99aba6b45fd030af91c",
            "quantity": 2
        }
    ],
    "paymentMethod": "tarjeta",
    "serveOption": "mesa"
}

### Actualizar el estado de una compra (protegido)
PUT http://localhost:3000/purchases/679ae9f6ba6b45fd030af926/status
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3OTcwYjU4NzkyNmQ0ZGRlZDM4YmUwYSIsImlhdCI6MTczODIwMzY3OCwiZXhwIjoxNzM4MjA3Mjc4fQ.BL8YAkK-xstd9kpoMfJmcc-fyGFFNOtwundSU-E6e6E
Content-Type: application/json

{
    "status": "completed"
}